//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJackGame.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBlackJack", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IBlackJack {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackJack/DealCard", ReplyAction="http://tempuri.org/IBlackJack/DealCardResponse")]
        string DealCard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackJack/Shuffle", ReplyAction="http://tempuri.org/IBlackJack/ShuffleResponse")]
        void Shuffle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackJack/GetHandValue", ReplyAction="http://tempuri.org/IBlackJack/GetHandValueResponse")]
        int GetHandValue(string delt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IBlackJackChannel : BlackJackGame.ServiceReference1.IBlackJack, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BlackJackClient : System.ServiceModel.ClientBase<BlackJackGame.ServiceReference1.IBlackJack>, BlackJackGame.ServiceReference1.IBlackJack {
        
        public BlackJackClient() {
        }
        
        public BlackJackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackJackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackJackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackJackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DealCard() {
            return base.Channel.DealCard();
        }
        
        public void Shuffle() {
            base.Channel.Shuffle();
        }
        
        public int GetHandValue(string delt) {
            return base.Channel.GetHandValue(delt);
        }
    }
}
