//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPClient.WelcomeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WelcomeService.IWelcomeSOAPService")]
    public interface IWelcomeSOAPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWelcomeSOAPService/Welcome", ReplyAction="http://tempuri.org/IWelcomeSOAPService/WelcomeResponse")]
        string Welcome(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWelcomeSOAPServiceChannel : SOAPClient.WelcomeService.IWelcomeSOAPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WelcomeSOAPServiceClient : System.ServiceModel.ClientBase<SOAPClient.WelcomeService.IWelcomeSOAPService>, SOAPClient.WelcomeService.IWelcomeSOAPService {
        
        public WelcomeSOAPServiceClient() {
        }
        
        public WelcomeSOAPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WelcomeSOAPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeSOAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeSOAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Welcome(string name) {
            return base.Channel.Welcome(name);
        }
    }
}
