//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
namespace InteractWithDB.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGateWayService")]
    public interface IGateWayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateWayService/SelectData", ReplyAction="http://tempuri.org/IGateWayService/SelectDataResponse")]
        System.Data.DataTable SelectData(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateWayService/InsertData", ReplyAction="http://tempuri.org/IGateWayService/InsertDataResponse")]
        bool InsertData(string sqlString, System.Data.SqlClient.SqlParameter[] parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateWayService/updateData", ReplyAction="http://tempuri.org/IGateWayService/updateDataResponse")]
        bool updateData(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGateWayService/testMessage", ReplyAction="http://tempuri.org/IGateWayService/testMessageResponse")]
        string testMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IGateWayServiceChannel : InteractWithDB.ServiceReference1.IGateWayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GateWayServiceClient : System.ServiceModel.ClientBase<InteractWithDB.ServiceReference1.IGateWayService>, InteractWithDB.ServiceReference1.IGateWayService {
        
        public GateWayServiceClient() {
        }
        
        public GateWayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GateWayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateWayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SelectData(string sqlString) {
            return base.Channel.SelectData(sqlString);
        }
        
        public bool InsertData(string sqlString, System.Data.SqlClient.SqlParameter[] parameter) {
            return base.Channel.InsertData(sqlString, parameter);
        }
        
        public bool updateData(string sqlString) {
            return base.Channel.updateData(sqlString);
        }
        
        public string testMessage() {
            return base.Channel.testMessage();
        }

        //protected override System.Net.WebRequest GetWebRequest(Uri uri)
        //{
        //    HttpWebRequest webRequest = (HttpWebRequest)base.GetWebRequest(uri);

        //    webRequest.KeepAlive = false;
        //    webRequest.ProtocolVersion = HttpVersion.Version10;
        //    return webRequest;
        //}
    }
}
